config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root  'static_pages#home'
  match '/about',   to: 'static_pages#about',   via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/arenda', to: 'static_pages#arenda', via: 'get'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def arenda
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title)
    base_title = "РУСЭМ"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    
  </small>
  <nav>
    <ul>
      <li><%= link_to "Главная",    root_path %></li>
              <li><%= link_to "О нас",    about_path %></li>
              <li><%= link_to "Контакты", contact_path %></li>
              <li><%= link_to "Аренда", arenda_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="navbar-inner">
        <div class="container">
          <%= link_to "СК РусЭМ (3812) 40-69-59", root_path, id: "logo" %>
          <nav>
            <ul class="nav pull-right">
              <li><%= link_to "Главная",    root_path %></li>
              <li><%= link_to "О нас",    about_path %></li>
              <li><%= link_to "Контакты", contact_path %></li>
              <li><%= link_to "Аренда", arenda_path %></li>
            </ul>
          </nav>
        </div>
      </div>
    </header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
   <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
    <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'О нас') %>
<h1>СТРОИТЕЛЬНАЯ КОМПАНИЯ "РУСЭМ"</h1>
<h3>Руководитель:  Русаков Станислав Васильевич</h3>
<h4>Телефон/факс (3812) 40-69-59</h4>
<p>Производство общестроительных работ</p>

<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ctHjS233XpomoXRC5DomqT2PIhoYWYNH&width=1280&height=659&lang=ru_RU&sourceType=constructor&scroll=true"></script>

app/views/static_pages/arenda.html.erb
arenda.html.erb

app/views/static_pages/contact.html.erb
<% provide(:title, 'Контакты') %>
<h2>Общество с ограниченной ответственностью «Строительная компания «РусЭМ» (ООО «СК «РусЭМ»)</h2>
<p>Телефон/факс:

(3812) 40-69-59
</p>
<p>
Е-mail:

sk-rusm@yandex.ru</p>

<script type="text/javascript" charset="utf-8" async src="https://api-maps.yandex.ru/services/constructor/1.0/js/?sid=ctHjS233XpomoXRC5DomqT2PIhoYWYNH&width=1280&height=659&lang=ru_RU&sourceType=constructor&scroll=true"></script>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
  <h1>Добро-пожаловать на</h1>

  <h2>
    Сайт Омской Строительной Компании РусЭМ
   </h2>

   
</div>

<%= image_tag("rails.jpg", alt: "RUSEM")  %>